version: "2.2"
services:
  master:
    build: .
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /config/spark
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_INSTANCES: 2
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 8080:8080
   volumes:
    - ./config:/config
    - ./jar:/jar
    - ./shell:/shell
    - ./logs:/logs

  worker:
    build: .
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /config/spark
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./config:/config
      - ./jar:/jar
      - ./shell:/shell
      - ./logs:/logs
